"""Created image many to one relationship with recipe table

Revision ID: 1b4fff37c257
Revises: afc3e84f6d5e
Create Date: 2020-06-02 14:42:24.819061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b4fff37c257'
down_revision = 'afc3e84f6d5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('id_recipe', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'image', 'recipe', ['id_recipe'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'image', type_='foreignkey')
    op.drop_column('image', 'id_recipe')
    # ### end Alembic commands ###
