"""Added recipe categories

Revision ID: 270a904b25a7
Revises: fc1fd98d2b96
Create Date: 2020-07-22 14:02:53.124717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '270a904b25a7'
down_revision = 'fc1fd98d2b96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_category_name'), 'category', ['name'], unique=True)
    op.add_column('recipe', sa.Column('source_type', sa.String(length=8), nullable=True))
    op.create_index(op.f('ix_recipe_source_type'), 'recipe', ['source_type'], unique=False)
    op.drop_index('ix_recipe_type', table_name='recipe')
    op.drop_column('recipe', 'type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('type', sa.VARCHAR(length=8), autoincrement=False, nullable=True))
    op.create_index('ix_recipe_type', 'recipe', ['type'], unique=False)
    op.drop_index(op.f('ix_recipe_source_type'), table_name='recipe')
    op.drop_column('recipe', 'source_type')
    op.drop_index(op.f('ix_category_name'), table_name='category')
    op.drop_table('category')
    # ### end Alembic commands ###
