"""Created date_added field in image table

Revision ID: fc1fd98d2b96
Revises: 649440289157
Create Date: 2020-06-03 12:26:20.297561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc1fd98d2b96'
down_revision = '649440289157'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('date_added', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('image', 'date_added')
    # ### end Alembic commands ###
